
trigger: none
 
pr: 
 branches:
   include:
   - main
   exclude:
   - dev
 paths:
   include:
   - '*'
   exclude:
   - docs
 autoCancel: false
 drafts: false

schedules:
- cron: 30 12 * Mar-Sep Mon,Wed,Fri
  branches: 
    include:
      - '*'
  always: false
  batch: true

resources:
 pipelines:
 - pipeline: dependantpipeline
   source: anonymous21155.mslearn-tailspin-spacegame-web
   trigger: true  
#repositories:
#- repository: templates
#  type: github
#  name: <org name/repo name>
#  endpoint: service connection name
stages:
- stage: A
# pool: sever (forserverless job)
  pool: 
    vmImage: 'windows-latest'
#   name: privateAgentName
#   demands: yourCondition  
#   container: 'public docker image' (container jobs)
#   image: "ACR -IMAGE name"
#   endpoint: 'sercie connection name'    
  jobs:
  - job: A1
    displayName: Install Dependencies
    continueOnError: false
    strategy:
#     parallel: 3 #System.TotalJobsInPhase indicates the total number of slices System.JobPositionInPhase identifies a particular slice
      maxParallel: 2
      matrix: 
        node_14x: 
          nodeVersion: 14.x
        node_16x:
          nodeVersion: 16.x
    timeoutInMinutes: 4
    cancelTimeoutInMinutes: 2
    steps:
    - script: |
        npm install
        npm run build
      enabled: true
      retryCountOnTaskFailure: 2
    - pwsh: ./script.ps1 # for PowerShell Core
      failOnStderr: true 
    - powershell: .\script.ps1 # for Windows PowerShell
    - bash: |
        echo hello
        which bash
#   - template: /templates/azure-pipelines-1.yml
#    workspace:
#      clean: resources (Build.SourcesDirectory) | outputs (Build.BinariesDirectory) | all (Pipeline.Workspace)

#   container: mcr.microsoft.com/windows/servercore:ltsc2019
  - job: A2
    displayName: Build the app
    dependsOn: A1
    condition: or(succeeded('A2'), and(eq(variables['build.sourceBranch'], 'refs/heads/main'), ne(variables['build.sourceBranch'], 'refs/heads/releases')))

  - job: A3
    displayName: Backup Job
#   dependsOn: [] (causes to run in parallel)
    condition: failed()
# - template: common.yml@templates #reference from another repo
    

