
trigger: none
 
pr: 
 branches:
   include:
   - main
   exclude:
   - dev
 paths:
   include:
   - '*'
   exclude:
   - docs
 autoCancel: false
 drafts: false

schedules:
- cron: 30 12 * Mar-Sep Mon,Wed,Fri
  branches: 
    include:
      - '*'
  always: false
  batch: true

resources:
 pipelines:
 - pipeline: dependantpipeline
   source: anonymous21155.mslearn-tailspin-spacegame-web
   trigger: true  

stages:
- stage: A
# pool: sever (forserverless job)
  pool: 
    vmImage: 'windows-latest'
#   name: privateAgentName
#   demands: yourCondition  
# container: 'public docker image' (container jobs)
#   image: "ACR -IMAGE name"
#   endpoint: 'sercie connection name'    
  jobs:
  - job: A1
    displayName: Install Dependencies
    continueOnError: false
    strategy:
      maxParallel: 2
      matrix: 
        node_14x: 
          nodeVersion: 14.x
        node_16x:
          nodeVersion: 16.x
    timeoutInMinutes: 4
    cancelTimeoutInMinutes: 2
#    workspace:
#      clean: resources (Build.SourcesDirectory) | outputs (Build.BinariesDirectory) | all (Pipeline.Workspace)

#   container: mcr.microsoft.com/windows/servercore:ltsc2019
  - job: A2
    displayName: Build the app
    dependsOn: A1