
trigger: none
 
pr: 
 branches:
   include:
   - main
   exclude:
   - dev
 paths:
   include:
   - '*'
   exclude:
   - docs
 autoCancel: false
 drafts: false

schedules:
- cron: 30 12 * Mar-Sep Mon,Wed,Fri
  branches: 
    include:
      - '*'
  always: false
  batch: true

resources:
 pipelines:
 - pipeline: dependantpipeline
   source: anonymous21155.mslearn-tailspin-spacegame-web
   trigger: true  

stages:
- stage: A
# pool: sever (forserverless job)
  pool: 
    vmImage: 'windows-latest'
  jobs:
  - job: A1
    displayName: Install Dependencies
    continueOnError: false
#   container: mcr.microsoft.com/windows/servercore:ltsc2019
  - job: A2
    displayName: Build the app
    dependsOn: A1