stages:
- stage: A
trigger: none
 
pr: 
 branches:
   include:
   - main
   exclude:
   - dev
 paths:
   include:
   - '*'
   exclude:
   - docs
 autoCancel: false
 drafts: false

schedules:
- cron: 30 12 * Mar-Sep Mon,Wed,Fri
  branches: 
    include:
      - '*'
  always: false
  batch: 

resources:
 pipelines:
 - pipeline: dependantpipeline
   source: anonymous21155.mslearn-tailspin-spacegame-web
   trigger: true
    
